# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rtwo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rtwo)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,95c21cefc487b832369caaa063b8407e2ced3880)
$(call add-radio-file-sha1-checked,radio/modem.img,93af66f3837242649664a4438bd2610ae44a2755)
$(call add-radio-file-sha1-checked,radio/abl.img,e98c54ee3151efcf275c0180b383149cf561a1f0)
$(call add-radio-file-sha1-checked,radio/aop.img,20ad4bc5b4bd428ee62bcc2a1654d4b6ca839121)
$(call add-radio-file-sha1-checked,radio/cpucp.img,8f57c29bad0b50b60a32374738a247c91284c52a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,12e6d9ba4b72e2cfd0d996c73d882c50cfcf2d8d)
$(call add-radio-file-sha1-checked,radio/dsp.img,cae6eca1ce7f0b237aa1a1a5e37b1092f54fdcb0)
$(call add-radio-file-sha1-checked,radio/fsg.img,5fe0f089b9d27083338e58ef8a96a0feda87df11)
$(call add-radio-file-sha1-checked,radio/hyp.img,f74bc8ea759ce787e877d9a2e5810241439b9d2d)
$(call add-radio-file-sha1-checked,radio/keymaster.img,65fb6874002295e8789c269a1c7e9536e9225304)
$(call add-radio-file-sha1-checked,radio/logo.img,1cdc90a57a62dbeece6aa87f85599bf20456f947)
$(call add-radio-file-sha1-checked,radio/prov.img,340fb0e3543a0c48e269a2e6dd8bcc55dc194af2)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b4c571958a53440c59fa563bfb57c6af56ef2477)
$(call add-radio-file-sha1-checked,radio/shrm.img,cd18a83b5abdcc2cf8dc18897c4345cce383d69f)
$(call add-radio-file-sha1-checked,radio/storsec.img,6d438bbfa3e2817b23c733fb0a3ecae261fa7939)
$(call add-radio-file-sha1-checked,radio/tz.img,0a0c5ed66fefad8fdec93f63c37712256f10f3a3)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,865c4a744b1b7a7618949a0c5c3cd0204db04733)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,510313280850115a86160064708803a2af2e639d)
$(call add-radio-file-sha1-checked,radio/xbl.img,20a88efbb2c49c968f4ce6aa51c44e73b246432c)

endif
