# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rtwo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rtwo)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,63a53f791a6fc300b2c9aeb4316f622e5958a8cb)
$(call add-radio-file-sha1-checked,radio/modem.img,b0cf28b16c7e7e20d8e07ee12c32c6e694be0cf9)
$(call add-radio-file-sha1-checked,radio/abl.img,b4b70d922c21b50ab2a15456a218f80fed7e021c)
$(call add-radio-file-sha1-checked,radio/aop.img,caf5a6b01430e364afd70ededba60750ef36139d)
$(call add-radio-file-sha1-checked,radio/cpucp.img,497bc89a40a02e7cabb41501e850a75b0f4b8e22)
$(call add-radio-file-sha1-checked,radio/devcfg.img,32ba968f998971950c4c9607e5f7afa2082c817d)
$(call add-radio-file-sha1-checked,radio/dsp.img,cae6eca1ce7f0b237aa1a1a5e37b1092f54fdcb0)
$(call add-radio-file-sha1-checked,radio/fsg.img,78a5a212fb364aa05b213f505f3559f66d097eb2)
$(call add-radio-file-sha1-checked,radio/hyp.img,b41a61a6958cfb3a784b36fc586b04e636a1d56b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,dd2974ef9561b04a771d95901863e41dd331cbba)
$(call add-radio-file-sha1-checked,radio/logo.img,f474764a853145bf4b62bc15c4f6197d342bb5fe)
$(call add-radio-file-sha1-checked,radio/prov.img,b242b77c27802ad3f4aa6d7d6f76f8cd082baf81)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ce8ddaec88ced2d240a05f538d033c85132eb08d)
$(call add-radio-file-sha1-checked,radio/shrm.img,c6af0870d4c958d4fd2f894adf046c6d49212f1d)
$(call add-radio-file-sha1-checked,radio/storsec.img,06d421acfae0d38cb55224bf7440ed96edf99d36)
$(call add-radio-file-sha1-checked,radio/tz.img,4496fb4afd0098cd5c53e9165835aa4974e6b8b7)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,0e0a1a78d674974d4f9e1da3e5672b49570a200e)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,371567334a80239acbd8db11757c8438e0647850)
$(call add-radio-file-sha1-checked,radio/xbl.img,b6e01068e6ec9e63b1907eb2c3a512a235e6cbf7)

endif
