# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rtwo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rtwo)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,48a1d54de29e7f4a08e46527a0d662ca915f5fb9)
$(call add-radio-file-sha1-checked,radio/modem.img,f0855633ce3c9714c1b51e1590bab29ae6638b7d)
$(call add-radio-file-sha1-checked,radio/abl.img,951633afaaed1286af000b9a59e39c7780c56127)
$(call add-radio-file-sha1-checked,radio/aop.img,4a551a57e08393fb5d64f5859b6940e08a51a940)
$(call add-radio-file-sha1-checked,radio/cpucp.img,1672b6ffbdbd6190117731c98e8033fb956d47f9)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f3001d2cda91a3a9715b694574d33ccc28ab69bd)
$(call add-radio-file-sha1-checked,radio/dsp.img,cae6eca1ce7f0b237aa1a1a5e37b1092f54fdcb0)
$(call add-radio-file-sha1-checked,radio/fsg.img,abe0336aacfbbfda08efe1a53a29d4fb5f7e92e0)
$(call add-radio-file-sha1-checked,radio/hyp.img,270b6e11914b86f4399cec04a55ad7940df3ec35)
$(call add-radio-file-sha1-checked,radio/keymaster.img,7916d92bd4926449fac50ab0a12570aa927f04d5)
$(call add-radio-file-sha1-checked,radio/logo.img,d0fbc4aad2d96a40b4937180eadd9cc70fd34bfe)
$(call add-radio-file-sha1-checked,radio/prov.img,d69e4f7b899269dc6667a4ea9e2d3bc06ff896c3)
$(call add-radio-file-sha1-checked,radio/qupfw.img,a590fbbe804cfdde5f4dd3309d36b9aec7e1bf54)
$(call add-radio-file-sha1-checked,radio/shrm.img,d600c7b3e43a7a33f60dc9ebe39808fb1402e963)
$(call add-radio-file-sha1-checked,radio/storsec.img,34821b10117af63a9e99aac769ab8c2a79495e13)
$(call add-radio-file-sha1-checked,radio/tz.img,66b987dbfa1edf0a90ede5d14563cdfabd247d9c)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9d812461abf9af61bc5c5245237478c50eef7058)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,b6f735b94a46ad72c8ac1f183059996426cccc5d)
$(call add-radio-file-sha1-checked,radio/xbl.img,89dd770567b61a251258507a360d2647e659f2db)

endif
